#auto: true

markdown: kramdown
pygments: true
paginate: 8
permalink: /:title/
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_hightlighter: rouge

title: LightningX' Blog
feed: /atom.xml
author_info: LightningX
