
markdown: kramdown
paginate: 8
permalink: /:title/
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_hightlighter: rouge
  syntax_hightlighter_opts:
    css_class: 'highlight'

title: LightningX' Blog
feed: /atom.xml
author_info: LightningX
